### ISSUE TITLE
Undefined method `new' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by soapjam** [anaynayak/aws-security-viz#95]
Hello,
I really interested to check your tool on my AWS infrastructure, but have following issue in runtime:

```
[ERROR] undefined method `new' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/aws_security_viz-0.2.0/lib/renderer/all.rb:7:in `pick': undefined method `new' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/aws_security_viz-0.2.0/lib/aws_security_viz.rb:23:in `unleash'
	from /Library/Ruby/Gems/2.3.0/gems/aws_security_viz-0.2.0/exe/aws_security_viz:30:in `<top (required)>'
	from /usr/local/bin/aws_security_viz:22:in `load'
	from /usr/local/bin/aws_security_viz:22:in `<main>'
```

I've tried several accounts and options and see same error. Did you see something like this before? 

I've installed your tool via gem on MacOS 10.14.6. Also I've tried to build Docker container locally and also getting following error:
```
docker build -t sec-viz .                                                   
Sending build context to Docker daemon  459.3kB
Step 1/5 : FROM ruby:2.6-alpine
 ---> 3304101ccbe9
Step 2/5 : RUN apk add --update graphviz ttf-ubuntu-font-family
 ---> Using cache
 ---> fb048111a474
Step 3/5 : RUN gem install aws_security_viz --pre
 ---> Running in e84926e61dc4
Building native extensions. This could take a while...
ERROR:  Error installing aws_security_viz:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ffi-1.11.3/ext/ffi_c
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20191218-1-1lwmj9u.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --enable-system-libffi
        --disable-system-libffi
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:672:in `try_ldflags'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:1832:in `pkg_config'
        from extconf.rb:9:in `system_libffi_usable?'
        from extconf.rb:34:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.6.0/ffi-1.11.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/ffi-1.11.3 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.6.0/ffi-1.11.3/gem_make.out
```

Sorry, but I don't observe any mkmf.log on my system as mentioned in log above. 

Could you please take a look on both issues above? Thanks in advance!

**Comment by soapjam** [comment]
Looks like it was issue on my side, thanks for your tool!
